### ISSUE TITLE
Key bindings not working properly

### ISSUE THREAD

**Issue by cjdango** [DrNseven/Ros-D3D#3]
Do you have an idea why insert and arrow keys are sometimes not working? If i hold it for a few seconds then it will work

**Comment by DrNseven** [comment]
Yes, (GetAsyncKeyState('key') **& 1** does not work well in this game. I fixed the key bindings today.

static int lasttick_insert = GetTickCount64();
if (GetAsyncKeyState(VK_INSERT) && GetTickCount64() - lasttick_insert > 100)
{
	lasttick_insert = GetTickCount64();
	ShowMenu = !ShowMenu;
	SaveCfg();
}
