### ISSUE TITLE
whats wrong with this unresolved symbol

### ISSUE THREAD

**Issue by codeneraka03** [DrNseven/Ros-D3D#5]

**Comment by DrNseven** [comment]
create an empty dll and add all minhook files to your project:
https://www.unknowncheats.me/forum/2032714-post72.html

**Comment by codeneraka03** [comment]
now I'm done with include { #pragma comment(lib,"D:/ROS/D3D/testing1/include/libMinHook.x86.lib") }

i make the project for .dll ..

thx bro
