### ISSUE TITLE
new Features

### ISSUE THREAD

**Issue by codeneraka03** [DrNseven/Ros-D3D#7]
Hello mate .

could you add some features like grave, fast para , speed hack , no fall damage
nor could you help me to find new offset for these features

**Comment by DrNseven** [comment]
Hi, I want to keep this base source d3d only, don't want to rely on offsets for memory hacks. Unknowncheats is probably the best place if you want help with finding offsets.

**Comment by codeneraka03** [comment]
hohoho i see...

btw thx before..
can i get your discord mate ?
